#! /usr/bin/env python
# -*- coding: utf-8 -*- 

import pandas
import numpy
import sys
from preprocess import translate_phone_brands

phone_brand_device_model = pandas.read_csv('csv/phone_brand_device_model.csv')
phone_brand_device_model = translate_phone_brands(phone_brand_device_model)

talkingdata = pandas.read_csv("csv/gender_age_train.csv")
talkingdata["brand"] = phone_brand_device_model["phone_brand"]

print(talkingdata.info())
print(talkingdata.head(n=10))

print(talkingdata.isnull().sum())
talkingdata["brand"] = talkingdata["brand"].fillna("Xiaomi")
print(talkingdata.isnull().sum())
