#! /usr/bin/env python

import pandas
import numpy
import re
import operator
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.cross_validation import KFold
from sklearn import cross_validation
import seaborn as sns
sns.set_style('whitegrid')
import matplotlib.pyplot as plt

# feature generation functions
def get_title(name):
    title_mapping = {"Mr": 1, "Miss": 2, "Mrs": 3, "Master": 4, "Dr": 5, "Rev": 6, "Major": 7, "Col": 7, "Mlle": 8, "Mme": 8, "Don": 9, "Lady": 10, "Countess": 10, "Jonkheer": 10, "Sir": 9, "Capt": 7, "Ms": 2, "Dona": 10}
    title_search = re.search('([A-Za-z]+)\.', name)
    if title_search:
        return title_mapping[title_search.group(1)]
    return ""

family_id_mapping = {}

def get_family_id(row):
    last_name = row["Name"].split(",")[0]
    family_id = "{0}{1}".format(last_name, row["FamilySize"])
    if family_id not in family_id_mapping:
        if len(family_id_mapping) == 0:
            current_id = 1
        else:
            current_id = (max(family_id_mapping.items(), key=operator.itemgetter(1))[1] + 1)
        family_id_mapping[family_id] = current_id
    return family_id_mapping[family_id]

# algorithms
def perform_logistic_regression(train_set, train_target, test_set):
    alg = LogisticRegression(random_state=1)
    alg.fit(train_set[predictors], train_target)
    predictions = alg.predict(test_set[predictors])
    scores = cross_validation.cross_val_score(alg, train_set[predictors], train_target, cv=3)
    print("LR scores: "+str(scores.mean()))
    return predictions

def perform_random_forest(train_set, train_target, test_set, estimators=178, splits=6, leafs=4):
    alg = RandomForestClassifier(random_state=1, n_estimators=estimators, min_samples_split=splits, min_samples_leaf=leafs)
    alg.fit(train_set[predictors], train_target)
    predictions = alg.predict(test_set[predictors])
    scores = cross_validation.cross_val_score(alg, train_set[predictors], train_target, cv=3)
    print("RF scores: "+str(scores.mean()))
    return predictions;

def perform_gradient_boosting(train_set, train_target, test_set, estimators=30, depth=3):
    alg = GradientBoostingClassifier(random_state=1, n_estimators=estimators, max_depth=depth)
    alg.fit(train_set[predictors], train_target)
    predictions = alg.predict(test_set[predictors])
    scores = cross_validation.cross_val_score(alg, train_set[predictors], train_target, cv=3)
    print("GB scores: "+str(scores.mean()))
    return predictions;


def perform_SVM(train_set, train_target, test_set):
    alg = SVC()
    alg.fit(train_set[predictors], train_target)
    predictions = alg.predict(test_set[predictors])
    scores = cross_validation.cross_val_score(alg, train_set[predictors], train_target, cv=3)
    print("SVM scores: "+str(scores.mean()))
    return predictions

def score_ensemble(algorithms, train_set, train_target):
    
    kf = KFold(titanic.shape[0], n_folds = 3, random_state=1)

    predictions = []
    for train, test in kf:

        full_test_predictions = []
        for alg, predictors in algorithms:

            fold_train_target = train_target.iloc[train]
            fold_train_predictors = train_set[predictors].iloc[train,:]

            alg.fit(fold_train_predictors, fold_train_target)

            # predict on the test fold
            # alg.predict will give the labels of the classified samples (i.e. 0 or 1)
            # alg.predict_proba will give the probability of a sample belonging to a category (i.e. 0~1)
            probability_array = alg.predict_proba(train_set[predictors].iloc[test,:].astype(float))
            # select probabilty of belonging to "Survived = 1"
            test_predictions = probability_array[:,1] 
            full_test_predictions.append(test_predictions)
        
        test_predictions = (full_test_predictions[0]*3 + full_test_predictions[1]*1) / 4 
        #test_predictions = (full_test_predictions[0]*2 + full_test_predictions[1]*1 + full_test_predictions[2]*1) / 4 
        test_predictions[test_predictions <= .5] = 0
        test_predictions[test_predictions > .5] = 1
        predictions.append(test_predictions)    

    # concatenate the three predicted test folders
    predictions = numpy.concatenate(predictions, axis=0)

    # Compute accuracy by comparing to the training data.
    accuracy = sum(predictions[predictions == train_target]) / len(predictions)
    print("Ensemble scores: "+str(accuracy))

def perform_ensemble(algorithms, train_set, train_target, test_set):
    total_predictions = []
    for algorithm, predictor in algorithms:

        algorithm.fit(train_set[predictors], train_target)
        prediction = algorithm.predict_proba(test_set[predictors].astype(float))[:,1]
        total_predictions.append(prediction)

    # gradient supposedly generates better predictions, so weight it higher
    predictions = ((total_predictions[0] * 3 ) + (total_predictions[1] * 1) )/ 4
    #predictions = ((total_predictions[0] * 2 ) + (total_predictions[1] * 1) + (total_predictions[2]*1) )/ 4

    predictions[predictions <= .5] = 0
    predictions[predictions > .5] = 1
    predictions = predictions.astype(int)
    return predictions

# util functions
def print_info(dataframe):
    print(dataframe.describe())
    print(dataframe.shape)

def generate_submission(dataframe, predictions):
    submission = pandas.DataFrame({
        "PassengerId": dataframe["PassengerId"],
        "Survived": predictions
    })
    submission.to_csv("kaggle.csv", index=False)

def feature_selection(dataframe, predictions):
    selector = SelectKBest(f_classif, k=5)
    selector.fit(dataframe[predictors], predictions)

    # Get the raw p-values for each feature, and transform from p-values into scores
    scores = numpy.log10(selector.pvalues_)
    
    plt.bar(range(len(predictors)), scores)
    plt.xticks(range(len(predictors)), predictors, rotation='vertical')
    plt.show()
    
def titanic_clean_data(dataframe):

    # fill mising values
    dataframe["Age"] = dataframe["Age"].dropna()
    dataframe["Age"] = dataframe["Age"].fillna(dataframe["Age"].median())
    dataframe["Fare"] = dataframe["Fare"].fillna(dataframe["Fare"].median())
    dataframe["Embarked"] = dataframe["Embarked"].fillna("S")

    # change non numeric columns to numeric
    dataframe.loc[dataframe["Sex"] == "male", "Sex"] = 0
    dataframe.loc[dataframe["Sex"] == "female", "Sex"] = 1
    dataframe.loc[dataframe["Embarked"] == "S", "Embarked"] = 0
    dataframe.loc[dataframe["Embarked"] == "C", "Embarked"] = 1
    dataframe.loc[dataframe["Embarked"] == "Q", "Embarked"] = 2

    # generating new features
    dataframe["FamilySize"] = dataframe["SibSp"] + dataframe["Parch"]
    dataframe["Title"] = dataframe["Name"].apply(get_title)
    family_ids = dataframe.apply(get_family_id, axis=1)
    family_ids[dataframe["FamilySize"] < 3] = -1
    dataframe["FamilyId"] = family_ids

    dataframe["Cabin"] = dataframe["Cabin"].fillna(0)
    dataframe.loc[dataframe["Cabin"] != 0, "Cabin"] = 1

    # drop unnecesesary columns, won't be helpful in analysis and prediction
    dataframe = dataframe.drop(['Name', 'Ticket'], axis=1)
    
    # discretize family size
    dataframe.loc[dataframe["FamilySize"] == 1, "FamilySize"] = -1
    dataframe.loc[dataframe["FamilySize"] > 5, "FamilySize"] = 0
    dataframe.loc[dataframe["FamilySize"] > 0, "FamilySize"] = 1

    #dataframe.loc[type(dataframe["Cabin"]) is str , "Cabin"] = 1

# read csv
titanic = pandas.read_csv("train.csv")
test = pandas.read_csv("test.csv")

#titanic.info()
#print('------------------------------------------')
#test.info()

titanic_clean_data(titanic)
titanic_clean_data(test)
#print(titanic.head(6))
 
predictors = ["Pclass", "Sex", "Age", "Cabin", "SibSp", "Parch", "Fare", "Embarked", "FamilySize",  "Title", "FamilyId"]
#predictors = ["Pclass", "Sex", "Title","Fare", "Embarked", "FamilyId"]

algorithms = [
    [GradientBoostingClassifier(random_state=1, n_estimators=35, max_depth=3), ["Pclass", "Sex", "Cabin", "Age", "Fare", "FamilySize", "Title", "FamilyId"]]
    #,[RandomForestClassifier(random_state=1, n_estimators=150, min_samples_split=4, min_samples_leaf=3), ["Pclass", "Sex", "Age", "Fare", "FamilySize", "Title", "FamilyId", "Embarked"]]
    #,[LogisticRegression(random_state=1), ["Pclass", "Sex", "Fare", "FamilySize", "Title", "Age" ,"Embarked"]]
    ,[SVC(probability=True), ["Pclass", "Sex", "Title", "Fare"]]
]

#predictions = perform_logistic_regression(titanic, titanic["Survived"], test)
#predictions = perform_random_forest(titanic, titanic["Survived"], test)
#predictions = perform_gradient_boosting(titanic, titanic["Survived"], test)
#predictions = perform_SVM(titanic, titanic["Survived"], test)
#score_ensemble(algorithms, titanic, titanic["Survived"])


#feature_selection(titanic[predictors], titanic["Survived"])
predictions = perform_ensemble(algorithms, titanic, titanic["Survived"], test)
generate_submission(test, predictions)
